using System.Net;
using System.Text;
using Easel.Core.Model;

namespace Easel.Output;

/// <summary>Self-contained offline HTML report (single file, inline CSS) for audits/clients.</summary>
public sealed class HtmlReportRenderer
{
    public string Render(LintReport report)
    {
        var s = report.Summary;
        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append($"<title>easel report — {H(report.Target)}</title>");
        sb.Append("<style>").Append(Css).Append("</style></head><body>");

        sb.Append("<header><h1>easel report</h1>");
        sb.Append($"<p class=\"meta\">{H(report.Tool)} {H(report.Version)} · target <code>{H(report.Target)}</code></p>");
        sb.Append("<div class=\"summary\">");
        sb.Append(Chip("error", s.Error));
        sb.Append(Chip("warning", s.Warning));
        sb.Append(Chip("info", s.Info));
        sb.Append($"<span class=\"chip total\">{s.Total} total</span>");
        sb.Append("</div></header>");

        if (report.Findings.Count == 0)
        {
            sb.Append("<p class=\"clean\">No findings 🎉</p>");
        }
        else
        {
            foreach (var group in report.Findings
                         .GroupBy(f => f.Location.IsKnown ? f.Location.File : "(app)")
                         .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase))
            {
                sb.Append($"<section><h2>{H(group.Key)}</h2><table>");
                sb.Append("<thead><tr><th>Loc</th><th>Severity</th><th>Rule</th><th>Message</th></tr></thead><tbody>");
                foreach (var f in group.OrderBy(f => f.Location.Line))
                {
                    var pos = f.Location.Line > 0 ? $"{f.Location.Line}:{f.Location.Column}" : "-";
                    sb.Append("<tr>");
                    sb.Append($"<td class=\"loc\">{H(pos)}</td>");
                    sb.Append($"<td><span class=\"sev {Sev(f.Severity)}\">{Sev(f.Severity)}</span></td>");
                    sb.Append($"<td><code>{H(f.RuleId)}</code><br><span class=\"rulename\">{H(f.RuleName)}</span></td>");
                    sb.Append($"<td>{H(f.Message)}{Help(f.Help)}</td>");
                    sb.Append("</tr>");
                }
                sb.Append("</tbody></table></section>");
            }
        }

        sb.Append($"<footer>Generated by {H(report.Tool)} {H(report.Version)}.</footer>");
        sb.Append("</body></html>");
        return sb.ToString();
    }

    private static string Chip(string sev, int n) => $"<span class=\"chip {sev}\">{n} {sev}</span>";
    private static string Help(string? help) => string.IsNullOrEmpty(help) ? "" : $"<div class=\"help\">{H(help!)}</div>";
    private static string Sev(Severity s) => s.ToString().ToLowerInvariant();
    private static string H(string s) => WebUtility.HtmlEncode(s);

    private const string Css = """
        :root { color-scheme: light dark; --bg:#fff; --fg:#1a1a1a; --muted:#666; --line:#e2e2e2; --card:#fafafa; }
        @media (prefers-color-scheme: dark) { :root { --bg:#16181d; --fg:#e6e6e6; --muted:#9aa0a6; --line:#2a2d34; --card:#1c1f26; } }
        * { box-sizing: border-box; } body { margin:0; padding:2rem; font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif; background:var(--bg); color:var(--fg); }
        h1 { margin:0 0 .25rem; font-size:1.6rem; } h2 { font-size:1rem; margin:1.5rem 0 .5rem; color:var(--muted); }
        .meta { color:var(--muted); margin:0 0 1rem; } code { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
        .summary { display:flex; gap:.5rem; flex-wrap:wrap; margin-bottom:1rem; }
        .chip { padding:.2rem .6rem; border-radius:999px; font-weight:600; font-size:.8rem; border:1px solid var(--line); }
        .chip.error,.sev.error { background:#fdecea; color:#b3261e; } .chip.warning,.sev.warning { background:#fff4e5; color:#8a5300; }
        .chip.info,.sev.info { background:#e8f0fe; color:#1a56b3; } .chip.total { background:var(--card); }
        @media (prefers-color-scheme: dark){ .chip.error,.sev.error{background:#3a1512;color:#f2b8b5}.chip.warning,.sev.warning{background:#3a2c10;color:#ffcf8f}.chip.info,.sev.info{background:#13233f;color:#a8c7fa} }
        table { width:100%; border-collapse:collapse; background:var(--card); border:1px solid var(--line); border-radius:8px; overflow:hidden; }
        th,td { text-align:left; padding:.5rem .75rem; border-bottom:1px solid var(--line); vertical-align:top; }
        th { font-size:.75rem; text-transform:uppercase; letter-spacing:.04em; color:var(--muted); }
        tr:last-child td { border-bottom:none; } .loc { color:var(--muted); white-space:nowrap; font-family:ui-monospace,monospace; }
        .sev { padding:.1rem .5rem; border-radius:4px; font-size:.75rem; font-weight:600; } .rulename { color:var(--muted); font-size:.8rem; }
        .help { color:var(--muted); font-size:.85rem; margin-top:.25rem; } .clean { font-size:1.2rem; }
        footer { margin-top:2rem; color:var(--muted); font-size:.8rem; }
        """;
}
